version: '3'
 
services:
  django:
    container_name: photoservice
    build: .
    environment:
      TEST_KEY: ${TEST_KEY}
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"